//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dan_LIII_Bojana_Backo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Floor { get; set; }
        public string Gender { get; set; }
        public string Citizenship { get; set; }
        public string Responsability { get; set; }
        public string Salary { get; set; }
        public int EmployeeID { get; set; }
    }
}
